define([
    './ticketcutoffs.list.controller',
    './ticketcutoffs.service',
    './ticketcutoffsdisplay',
    './ticketcutoffsedit',
    './ticketcutoffsadd',
    './ticketpricesareaslist',
    './ticketpricesareasdetails',
]);